### ISSUE TITLE
Upgrade Swift package

### ISSUE THREAD

**Issue by chadrickman** [Tealium/tealium-flutter#15]
While investigating #14 I took note that the swift package is outdated.

**Comment by ShivamPage** [comment]
Hello, I am having issues while running IOS after upgrading to 2.8.1 flutter SDK. it's showing an error in Native files for telium on IOS Side. When can we expect the fix, it has become a blocker for my upgrade. As rest of the packages are working fine!
@craigrouse 

@chadrickman  did you find any solution for this?

**Comment by craigrouse** [comment]
Closing this, since the plugin has now been upgraded.
