### ISSUE TITLE
Add support for null safety

### ISSUE THREAD

**Issue by chadrickman** [Tealium/tealium-flutter#2]
Flutter 2 has been released with [null safety](https://dart.dev/null-safety/migration-guide) for Dart. Is this something you plan to add support for to enable upgrades?

**Comment by jameskeith** [comment]
@chadrickman 
as mentioned on one of the other issues (https://github.com/Tealium/tealium-flutter/issues/3) we'll be updating the underlying SDKs that we use, so I've made a note that we consider adding support for this in the next release.

**Comment by christinasund** [comment]
Closing this issue as well, see  issue #3
