### ISSUE TITLE
Upgrade Android and iOS native packages

### ISSUE THREAD

**Issue by chadrickman** [Tealium/tealium-flutter#3]
The currently 1.2.0 is running the following outdated native packages:

- 5.7.0 (Android) (Current version: 5.9.1)
- 5.6.6 (iOS) (Current version: 5.8.0)

Are there plans to upgrade the native packages to the latest version?

**Comment by jameskeith** [comment]
Hi @chadrickman 
Thanks for raising this with us - we're in the process of updating our cross-platform libraries (Flutter included) to depend upon our [tealium-kotlin](https://github.com/Tealium/tealium-kotlin) and [tealium-swift](https://github.com/Tealium/tealium-swift) sdks
I don't have an exact timeline as of yet, but as a result there are not plans to update to the latest of our Java (5.9.1)/ObjC (5.8.0) sdks at this time.

**Comment by christinasund** [comment]
@chadrickman We have upgraded our flutter plugin to use null safety and the latest Tealium Swift and Tealium Kotlin libraries.  Hopefully, this works well for you, let us know if you have any issues upgrading.
