### ISSUE TITLE
Android dependency using unsafe or unchecked operations.

### ISSUE THREAD

**Issue by chadrickman** [Tealium/tealium-flutter#4]
Getting the following warning when building for Android.

```
tealium-1.2.0/android/src/main/java/com/tealium/TealiumPlugin.java uses unchecked or unsafe operations.
```

**Comment by jameskeith** [comment]
@chadrickman thanks for raising this with us
we can certainly address this in the next release.

**Comment by christinasund** [comment]
Closing this one too, see issue #3
