### ISSUE TITLE
Namespace not specified

### ISSUE THREAD

**Issue by sooslevi9** [Tealium/tealium-flutter#43]
tealium: ^2.5.0

1: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':tealium'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file: /Users/laszlo.soos/.pub-cache/hosted/pub.dev/tealium-2.5.0/android/build.gradle. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Failed to query the value of property 'buildFlowServiceProperty'.
> Could not isolate value org.jetbrains.kotlin.gradle.plugin.statistics.BuildFlowService$Parameters_Decorated@3a9a38ac of type BuildFlowService.Parameters
   > A problem occurred configuring project ':tealium'.
      > Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
         > Namespace not specified. Specify a namespace in the module's build file: /Users/abc/.pub-cache/hosted/pub.dev/tealium-2.5.0/android/build.gradle. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

           If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

BUILD FAILED in 8s
Error: Gradle task assembleDevelopmentDebug failed with exit code 1

![image](https://github.com/user-attachments/assets/cb15f707-6d10-4571-81da-80f38be06d2e)

android/build.gradle

`buildscript {
    ext.kotlin_version = '1.9.23'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.5.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
`

**Comment by michalkos** [comment]
This is blocking issue, when using AGP 8. Any resolution?

**Comment by jameskeith** [comment]
@michalkos @sooslevi9 
Thanks for your patience on this one - we've just published updates to all the packages that we support, since they all suffered the same issue as the main `tealium` package.

I'm afraid it took a while to verify support across a wide range of Android/AGP versions which we look to maintain, so we've pulled in some additional changes present in the newer Flutter plugin templates to hopefully make these packages more reliable going forward.

In case it's useful for you or anyone else reading this, most issues of this nature can be worked-around in Gradle. For example, in this instance, since the `tealium` package creates it's own module in your Android Studio project, those missing requirements can be set from root project's `build.gradle`:
```groovy
allprojects {
    // repositories omitted ...

    subprojects {
        afterEvaluate { project ->
            if (project.name == "tealium" && project.hasProperty("android")) {
                project.android {
                    if (project.android.hasProperty("namespace") && project.android.namespace == null) {
                        namespace = 'com.tealium'
                    }
                    // set any other required fields e.g.
                    buildFeatures {
                        buildConfig true
                    }
                }
            }
        }
    }
}
```
I'll also note/concede that this isn't gradle best-practice - it's definitely a workaround.

Please let me know how you get on with the latest versions.
